### ISSUE TITLE
Explanations or Citations

### ISSUE THREAD

**Issue by anseljh** [kemitchell/american-legal-archaisms#1]
It might be nice to be able to record citations to authorities. For example, for "by and between", I might record `MSCD3 2.46` to cite section 2.46 of the Third Edition of [_A Manual of Style for Contract Drafting_](http://www.adamsdrafting.com/writing/MSCD/).

A more general field for explanations or other notes could also do the trick.

**Comment by kemitchell** [comment]
If you're thinking about Common Form, I have good news!

This package is basically just a JSON file with a list of words. [commonform-critique](https://www.npmjs.com/package/commonform-critique) has the actual JavaScript that checks for these words in Common Forms [here](https://github.com/commonform/commonform-critique/blob/master/rules/archaisms.js). Look for `require('american-legal-archaisms')`.

commonform-critique is one of a few modules, existing an planned, that take a Common Form in and spit "annotations" out. [commonform-annotations](https://www.npmjs.com/package/commonform-annotations) describes the format of those annotations. In addition to a `message` property, which might mention MSCD, they can have a URL.

I believe the web interface rewrite already checks for a URL and turns the annotation into a hyperlink if it can.

**Comment by anseljh** [comment]
Cool. I figured it would be something like that. But where do you write the `message`s?

**Comment by kemitchell** [comment]
The relevant code in commonform-critique is [here](https://github.com/commonform/commonform-critique/blob/master/rules/archaisms.js#L20).

On a related note, I fully intend to write an additional commonform-mscd (or similar) that addresses MSCD directly. Some folks might want to zap archaisms without seeing all the hints MSCD has to offer. There's no harm in having multiple modules annotate the same issue.
