### ISSUE TITLE
Redudant reptition of numbers and numerals

### ISSUE THREAD

**Issue by anseljh** [kemitchell/american-legal-archaisms#3]
How do you want to handle redundant numbers, _e.g._, "two (2)"?

We could write out at least one through ten (1-10) or so, but what would be an appropriate more general approach to this class of repeated redundancy and re-recital?

**Comment by kemitchell** [comment]
I think we see eye to eye on that practice, but I wouldn't call it archaic, just error-prone.

I'd definitely like to add those checks---probably based on a regex---to an annotator. But this package hopefully stays a very small list of words and phrases.

**Comment by kemitchell** [comment]
Thanks for this.

I think we see eye to eye on that practice, but I wouldn't call it archaic, just error-prone.

I'd definitely like to add those checks---probably based on a regex---to an annotator. But this package hopefully stays a very small list of words and phrases.

Perhaps you'd like to open an issue on [commonform-critique](https://github.com/commonform/commonform-critique)

**Comment by anseljh** [comment]
The action is at https://github.com/anseljh/doubleplus-numbers.
