### ISSUE TITLE
Check list from mcchan1/legalese

### ISSUE THREAD

**Issue by anseljh** [kemitchell/american-legal-archaisms#5]
https://github.com/mcchan1/legalese/blob/master/legalese.py

``` python
#dictionary of useless legal terms
legal_dict = {'ab initio':'from the start',
'accord': 'give',
'afforded':'given',
'aforementioned':'this',
'aforesaid': 'this',
'albeit':'although' ,
'ambit':'scope',
```

...

**Comment by kemitchell** [comment]
"Ab initio", "aforementioned", and "aforesaid" strike me as archaic. I'm not sure about the rest.

"Accord", "albeit", and "ambit" might belong in wordy-words.
